GoogleCloudPlatform/PerfKitExplorer

- client/components/explorer/explorer-service.js
- client/components/widget/data_viz/gviz/gviz-directive.js
Previously was only taking place on refresh.
> Apply parameters to queries on dashboard load.

- README.md
Reverts GoogleCloudPlatform/PerfKitExplorer#97
> Revert "Remove deprecated step in gcloud install"

- README.md
Markdown takes care of numbering the list items automatically. This way
it's easier to insert or reorder items, and it also avoids spurious
diffs due to manual renumbering.
> README.md: change ordered list numbers to "1." in Markdown source.

- client/components/widget/data_viz/gviz/chart-config-directive.html
- client/components/widget/data_viz/gviz/chart-wrapper-service.js
The chart sidebar UX now includes a combo box for choosing the Legend position.
> Add a legend position dropdown to the chart config

- client/components/layout/fill-directive.js
- client/components/widget/query/builder/query-builder-filter-config-directive.html
- client/components/widget/query/builder/relative-datepicker-directive.js
- client/components/widget/query/query-editor-service.js
- client/components/widget/query/query-editor-service_test.js
- client/karma.conf.js
Also fixes an issue with date popup styling.
> Fix lingering ngInject issues.

- client/components/container/container-directive.css
- client/components/dashboard/dashboard-directive.html
- client/components/widget/widget-directive.css
Selection now correctly highlights, and containers/widgets no longer have a 1px adjustment as container selection changes.
> Fixed selection and alignment issues in container.

- client/components/container/container-config-directive.html
- client/components/explorer/sidebar/sidebar-tab-service.js
* Container tab now appears when no widget is selected.
> Move dashboard and container tabs to the top of the list.

- client/app.js
- client/components/container/container-toolbar-directive.html
- client/components/container/container-toolbar-directive.js
- client/components/container/container-toolbar-directive_test.js
- client/components/dashboard/dashboard-config-directive.css
- client/components/dashboard/dashboard-service.js
- client/components/dashboard/dashboard-service_test.js
- client/components/dashboard/dashboard-toolbar-directive.html
- client/components/dashboard/dashboard-toolbar-directive.js
- client/components/dashboard/dashboard-toolbar-directive_test.js
- client/components/error/error_service.js
- client/components/explorer/explorer-header-directive.css
- client/components/explorer/explorer-header-directive.html
- client/components/explorer/explorer-header-directive.js
- client/components/explorer/explorer-page-directive.css
- client/components/explorer/explorer-page-directive.html
- client/components/explorer/explorer-service.js
- client/components/explorer/explorer-toolbar-directive.css
- client/components/explorer/explorer-toolbar-directive.html
- client/components/explorer/explorer-toolbar-directive.js
- client/components/explorer/sidebar/sidebar-tab-service.js
- client/components/explorer/sidebar/sidebar-tabs-directive.js
- client/components/log/log-directive.js
- client/components/widget/query/widget-editor-directive.css
- client/components/widget/query/widget-editor-directive.html
- client/components/widget/widget-config-directive.css
- client/components/widget/widget-toolbar-directive.html
- client/components/widget/widget-toolbar-directive.js
- client/components/widget/widget-toolbar-directive_test.js
- client/css/base.css
* Moved toolbars to the right of the selected panel.
* Made toolbar selection dependent on selected panel.
* Moved global buttons (log, options) to the title.
* Restyled the title/header.
* Updated footer styling.
* Updates to color and shading for tab categories.
> Improved toolbar display and selection

- client/components/dashboard/dashboard-toolbar-directive.js
- client/components/dashboard/dashboard-toolbar-directive_test.js
Also adds function-level unit tests to DashboardToolbarDirective.
> Fix dashboard delete

- server/perfkit/explorer/handlers/dashboard.py
Also added a TODO to add paging or something more intelligent in the future.
> Raise limit of dashboards returned from 1k to 2k.

- client/app.js
- client/components/code_editor/code-editor-controller_test.js
- client/components/container/container-service.js
- client/components/container/container-service_test.js
- client/components/container/container-toolbar-directive.html
- client/components/container/container-toolbar-directive.js
- client/components/container/container-toolbar-directive_test.js
- client/components/dashboard/dashboard-directive.html
- client/components/dashboard/dashboard-directive.js
- client/components/dashboard/dashboard-service.js
- client/components/dashboard/dashboard-service_test.js
- client/components/dashboard/dashboard-toolbar-directive_test.js
- client/components/explorer/explorer-service.js
- client/components/explorer/explorer-service_test.js
- client/components/explorer/explorer-state-model.js
- client/components/explorer/sidebar/sidebar-tab-service_test.js
- client/components/explorer/sidebar/sidebar-tabs-directive_test.js
- client/components/util/array-util-service.js
- client/components/util/array-util-service_test.js
- client/components/widget/data_viz/gviz/gviz-directive_test.js
- client/components/widget/data_viz/widget-editor-controller_test.js
- client/components/widget/query/builder/query-builder-column-config-directive_test.js
- client/components/widget/query/builder/query-builder-filter-config-directive_test.js
- client/components/widget/query/query-result-config-directive_test.js
- client/components/widget/widget-toolbar-directive_test.js
- compile.sh
Moved container move logic into ContainerService.
Moved dashboard initialization to ExplorerService.
> Refactor array move into util service.

- client/components/container/container-service.js
- client/components/container/container-service_test.js
This issue occurred after using the Insert After and Insert Before actions.
> Fixed an issue where containers were not properly selected

- client/components/widget/data_viz/gviz/gviz-charts.json
- server/perfkit/explorer/handlers/templates/explorer.html
See https://developers.google.com/chart/interactive/docs/gallery/annotationchart for a description of the chart.
> Add AnnotationChart.

- client/components/config/config-service_test.js
- client/components/container/container-service.js
- client/components/dashboard/dashboard-service.js
- client/components/dashboard/dashboard-service_test.js
- client/components/explorer/sidebar/sidebar-tabs-directive_test.js
- client/components/widget/widget-factory-service_test.js
* Also fixes an issue introduced in the latest Karma that breaks describe() blocks with the name 'toJSON'.
> Fix general issues in widget/container selection.

- client/components/config/config-dialog.css
- client/components/widget/data_viz/gviz/chart-wrapper-service.js
- client/components/widget/data_viz/gviz/gviz-directive.js
- client/components/widget/data_viz/widget-editor-controller.js
- client/components/widget/data_viz/widget-editor-service.js
* The dialog should reflect the contents of the data view, and no longer refresh.
* The dialog will no longer overwrite custom column settings.
> Improve behavior of chart dialog.

- client/components/config/config-dialog.css
- client/components/config/config-directive.html
- client/components/config/config-service.js
- client/components/config/config-service_test.js
- client/components/widget/query/query-result-data-service.js
- client/components/widget/query/query-result-data-service_test.js
- server/perfkit/explorer/handlers/base.py
- server/perfkit/explorer/handlers/data.py
- server/perfkit/explorer/handlers/data_test.py
- server/perfkit/explorer/model/dashboard.py
- server/perfkit/explorer/model/dashboard_test.py
- server/perfkit/explorer/model/explorer_config.py
- server/perfkit/explorer/model/explorer_config_test.py
- server/perfkit/explorer/util/explorer_config_util.py
- server/perfkit/explorer/util/explorer_config_util_test.py
- test/js/globals.js
For full design, see https://goo.gl/ZoBzX7.
> Admin settings to control dashboard/query access for non-admins

- client/components/dashboard_admin_page/dashboard-admin-page-directive.html
- client/components/explorer/explorer-header-directive.html
> Fix gear dropdown menu to adhere to Bootstrap v14 standard.

- server/perfkit/explorer/handlers/data.py
- server/perfkit/explorer/handlers/data_test.py
> Fix issue with queries on unsaved dashboards.

- client/components/dashboard_admin_page/dashboard-admin-page-directive.html
- client/components/explorer/explorer-header-directive.html
- client/components/util/type-util.js
- client/components/util/type-util_test.js
- client/components/widget/query/builder/query-builder-service.js
- client/components/widget/query/builder/query-builder-service_test.js
> Fix QueryBuilder support for official filter

- client/components/container/container-service.js
- client/components/container/container-toolbar-directive.html
- client/components/container/container-toolbar-directive.js
- client/components/container/container-toolbar-directive_test.js
- client/components/widget/query/builder/query-builder-service_test.js
- client/components/widget/widget-toolbar-directive.js
- client/components/widget/widget-toolbar-directive_test.js
> Widget delete confirm

- client/components/dashboard_admin_page/dashboard-admin-page-controller.js
This is to workaround an issue/lack of clarity on changing the date format for filter textboxes in UI grid:
https://github.com/angular-ui/ui-grid/issues/4806
> Adjust date format to match filter format.

- bower.json
- client/app.js
- client/components/container/container-config-directive.html
- client/components/container/container-config-directive.js
- client/components/dashboard/dashboard-directive.html
- gulpfile.js
- server/perfkit/explorer/handlers/templates/explorer.html
- server/perfkit/explorer/handlers/templates/third-party-scripts.html
Uses the Angular Markdown component by btford, which uses the Showdown markdown engine.
http://showdownjs.github.io/demo/
> Adds Markdown support to container header/footer.

- bower.json
- client/app.js
- client/components/dashboard/dashboard-directive.css
- client/components/dashboard/dashboard-directive.html
- gulpfile.js
- server/perfkit/explorer/handlers/templates/third-party-scripts.html
Updates to the latest showdown version and enables tables.
> Changed from angular-markdown to ng-showdown directive.

- client/components/container/container-config-directive.html
- client/components/container/container-model.js
- client/components/dashboard/dashboard-directive.css
- client/components/dashboard/dashboard-directive.html
- client/components/widget/widget-config-directive.html
- client/components/widget/widget-directive.css
Also adds optional explicit header/footer heights for containers and widgets, to control layout.
> Add Widget header/footer

- client/components/code_editor/code-editor-controller.js
- client/components/code_editor/code-editor-settings-model.js
- client/components/widget/query/widget-editor-directive.html
This is deployed with 26.2 at https://26-2-dot-perfkit-explorer.googleplex.com
> Add footer tab to show the last query executed.

- client/components/container/container-config-directive.html
- client/components/dashboard/dashboard-directive.html
- client/components/dashboard/dashboard-directive.js
- client/components/dashboard/dashboard-service.js
- client/components/explorer/sidebar/sidebar-directive.html
- client/components/explorer/sidebar/sidebar-tab-service.js
- client/components/widget/widget-config-directive.html
- client/components/widget/widget-config-directive.js
- client/components/widget/widget-directive.css
- client/components/widget/widget-directive.js
- client/components/widget/widget-factory-service.js
- client/components/widget/widget-toolbar-directive.html
- client/components/widget/widget-toolbar-directive.js
- client/models/widget_model.js
* Add an option to use markdown in the widget.
* Add an option to scroll overflow content in the widget, rather than stretch.
> Markdown widgetbody

- client/components/container/container-directive.css
- client/components/dashboard/dashboard-directive.html
- client/components/dashboard/dashboard-directive.js
- client/components/explorer/explorer-page-directive.css
- client/components/widget/widget-directive.css
- client/css/base.css
Demo at https://26-6-dot-perfkit-explorer.appspot.com
> Update visual styling for widgets and containers

- server/perfkit/explorer/handlers/templates/explorer.html
This is inappropriately removed several versions back.
> Add pageview GA tracking.

- app.yaml
- server/perfkit/common/gae_cloud_sql_client.py
- server/perfkit/explorer/handlers/data.py
Initial cloud SQL backend code.
Intended for merging into the **dev-cloudsql** branch, not master.
> Cloud SQL backend code

- client/components/dashboard/dashboard-directive.html
- client/components/dashboard/dashboard-directive.js
- client/components/widget/widget-directive.html
- client/components/widget/widget-directive.js
Fixes miscellaneous issues in widget selection involving dead zones (from the margin/padding between elements).
> Clean up widget selection to be more consistent and eliminate dead zones

- client/components/dashboard/dashboard-directive.html
This is deployed on https://27-2-dot-perfkit-explorer.appspot.com
> Hide vertical overflow on nonscrollable widgets.

- client/components/widget/data_viz/gviz/column_style/column-style-toolbar-directive.html
- client/components/widget/data_viz/gviz/column_style/column-style-toolbar-directive.js
Also reorganized buttons and adds separators.
> Add refresh, edit sql/json and SQL builder buttons to column toolbar.

- client/components/explorer/explorer-header-directive.html
- client/components/explorer/explorer-header-directive.js
- client/components/explorer/explorer-header-directive_test.js
This functionality can be demo'ed on [v28.3](https://28-3-dot-perfkit-explorer.appspot.com/)
> Add Delete Confirmation dialog to "gear menu" dashboard delete

- client/components/dashboard/dashboard-version-service.js
- client/components/dashboard/versions/dashboard-schema_12.js
- client/components/widget/data_viz/gviz/chart-config-directive.html
- client/components/widget/data_viz/gviz/chart-wrapper-service.js
- client/components/widget/data_viz/gviz/column_style/column-style-directive.html
- client/components/widget/data_viz/gviz/column_style/column-style-directive_test.js
- client/components/widget/data_viz/gviz/column_style/column-style-model.js
- client/components/widget/data_viz/gviz/column_style/column-style-service.js
- client/components/widget/data_viz/gviz/column_style/column-style-service_test.js
- client/components/widget/data_viz/gviz/gviz-directive.css
- client/models/chart_widget_model.js
This is deployed on [v28.3](https://28-3-dot-perfkit-explorer.appspot.com).  You can see a demo and instructions on how to enable the feature on the [Tooltip Sample Dashboard](https://28-3-dot-perfkit-explorer.appspot.com/explore?dashboard=5710999223009280).
> Add HTML Tooltip Support
