GoogleCloudPlatform/PerfKitExplorer

.gitignore, README.md, client/app.js, compile.cmd, compile.sh, gulpfile.js, package.json, server/perfkit/explorer/handlers/templates/dashboard-admin.html, server/perfkit/explorer/handlers/templates/explorer.html
This compiles the .html templates into /client/perfkit_template.js, which will prevent caching in the future and improve performance.
=> Add grunt compiler and html2js templates

client/components/alert/error_service.js, client/components/dashboard/dashboard-service.js, client/components/widget/data_viz/gviz/gviz-directive_test.js
* Fix issue with gviz tests failing due to missing global config for project, dataset, table, etc.
* Improve error messaging when project, dataset, table, etc. values cannot be found in the widget, dashboard or global scopes.
* Add an option to the error service to log to console, and default to true.
=> Fix gviz test and improve error messaging.

compile.sh, gulpfile.js, package.json
* fix compile.sh to exit on errors instead of continuing after failed steps.
* add sanity check to verify we're in the right directory, especially
considering that the first thing it does is a "rm -rf".
* use build/ directory for generated build artifacts consistently:
* Write compiled JS code to build/perfkit_scripts.js instead of client/.
This avoids the "Circular dependency detected" error it otherwise gets when recompiling,
and avoids having git complain about an untracked file. Uses 'gulp-flatten' module.
* Write CSS to build/perfkit_styles.css instead of out/.
* Add a try/catch around toplevel imports so that there's a friendlier error
message when a required module is missing. See example: https://gist.github.com/klausw/573418af6061dc83fecd
=> Sanity checks and tweaks to compile environment

client/components/container/container-model.js, client/components/dashboard/dashboard-model.js, client/components/dashboard_admin_page/dashboard-admin-page-model.js, client/components/widget/query/query-editor-controller.js, client/components/widget/widget-factory-service.js, client/models/widget_model.js
@expose is a deprecated means in the Closure compiler for preventing a symbol from being obfuscated/minified. This allows html templates to correctly reference property and method names.  @export is the preferred decorator for this behavior.
=> Changed @expose to @export

client/components/popupbox/popupbox-directive.js, client/components/popupbox/popupbox-directive_test.js, client/components/widget/query/builder/query-builder-column-config-directive.html, client/components/widget/query/builder/query-builder-filter-config-directive.html, client/components/widget/query/builder/query-builder-filter-config-directive_test.js
Reverts an earlier change made to popupbox to support dynamic templates.  As a directive's templateUrl resolver doesn't have access to the scope, driving the template selection from the html using dynamic values (such as goog.string functionality or relying on data/constants from services) is problematic and will require a more complicated workaround.
Also fixes a styling issue with the end date filter close button.
=> Fix popupbox

client/app.js, client/components/explorer/explorer-router-config.js, client/components/explorer/explorer-state-model.js, client/components/explorer/explorer-state-model_test.js, client/components/explorer/explorer-state-service.js, client/components/explorer/explorer-state-service_test.js, client/karma.conf.js
Adds the management classes (Service and Model) for Explorer State, based on the current values in the Angular UI Router state service.  At the moment, these services are loaded but unused; additional PR's will consolidate the dashboard's selection state into this service.
For more info, see the [Design Doc](https://docs.google.com/presentation/d/1e6CFF4-qdCKnNROCE4EL4qFjewtnBHxMCJ1IXJZ8N6k/edit#slide=id.p)
=> Add explorer state

client/app.js, client/components/dashboard/dashboard-version-service.js, client/components/dashboard/versions/dashboard-schema_09.js, client/components/explorer/explorer-toolbar-directive.html, client/components/explorer/sidebar/sidebar-directive.html, client/components/explorer/sidebar/sidebar-tab-service.js, client/components/widget/data_viz/gviz/column_style/column-style-config-directive.html, client/components/widget/data_viz/gviz/column_style/column-style-config-directive.js, client/components/widget/data_viz/gviz/column_style/column-style-directive.css, client/components/widget/data_viz/gviz/column_style/column-style-directive.html, client/components/widget/data_viz/gviz/column_style/column-style-directive.js, client/components/widget/data_viz/gviz/column_style/column-style-directive_test.js, client/components/widget/data_viz/gviz/column_style/column-style-model.js, client/components/widget/data_viz/gviz/column_style/column-style-service.js, client/components/widget/data_viz/gviz/column_style/column-style-service_test.js, client/components/widget/data_viz/gviz/column_style/column-style-toolbar-directive.html, client/components/widget/data_viz/gviz/column_style/column-style-toolbar-directive.js, client/components/widget/data_viz/gviz/column_style/column-style-toolbar-directive_test.js, client/components/widget/data_viz/gviz/gviz-directive.js, client/components/widget/data_viz/gviz/gviz-directive_test.js, client/components/widget/query/data-view-service.js, client/mocks/mocks.js, client/models/chart_widget_model.js
* A new Columns tab is now available when a widget is selected.
* Column styles can be added, providing a column id (the field from your SQL query) and an optional title.  Specifying a title will use the provided value in place of the axis/legend/series title in a chart or table.
* Column styles can be reordered.  This will cause the chart/table columns to appear in the same order.
* note: this has no effect if you're using the view.columns in json, or using the pivot's "sort columns" feature.  UX for both of these will be folded into the Columns sidebar before release.
* If a column is not specified in the styles UX but is present in the dataTable, it will be appended to the end of the table/view.
=> Initial Column Style support

client/components/dashboard/dashboard-service.js, client/components/dashboard/dashboard-service_test.js, client/components/explorer/explorer-service.js, client/components/explorer/sidebar/sidebar-tab-service.js, client/components/explorer/sidebar/sidebar-tab-service_test.js
Also changes the icon to a box, and fixes an issue with selecting the top widget when initially loading the dashboard or selecting a widget.
=> Move Widget Config tab to the top of widget tabs

client/components/dashboard/dashboard-directive.html, client/components/dashboard/dashboard-directive.js, client/components/dashboard/dashboard-service.js, client/components/explorer/explorer-service.js, client/components/explorer/explorer-state-service.js, client/components/explorer/explorer-state-service_test.js, client/components/explorer/sidebar/sidebar-directive.html, client/components/explorer/sidebar/sidebar-tab-model.js, client/components/explorer/sidebar/sidebar-tab-service.js, client/components/explorer/sidebar/sidebar-tab-service_test.js, client/components/explorer/sidebar/sidebar-tabs-directive.html, client/components/explorer/sidebar/sidebar-tabs-directive.js
* Containers can now be selected by clicking on them
* The Container tab will only show when a container is selected (this implicitly includes widget selection)
* The Sidebar will no longer open when the page loads to a container/widget
* If a Container is selected (but no widget), it will be scrolled into view
=> Improve Container Selection

client/components/dashboard/dashboard-service.js
On initial load, currentWidget === widget but its widget model state is
not set as selected. Instead of special casing it, just clear
the old widget model selected state unconditionally.
=> Fix widget selection state on reload.

client/components/container/container-service.js, client/components/dashboard/dashboard-service.js, client/components/query_builder/query-builder.js, client/components/widget/query/builder/query-builder-service.js, client/components/widget/query/data-view-service.js, gulpfile.js, server/perfkit/explorer/handlers/base.py, server/perfkit/explorer/handlers/templates/third-party-scripts.html
This is initially intended for discussion - the change currently uses un-minified Angular unconditionally,
not sure if that's acceptable for performance.
I've also tried to use the minified version with a source map, this now works for source code locations but not for the renamed variables, making debugging nearly impossible. So I wouldn't recommend that variant.
=> Transpile to ES5_STRICT, use un-minified code.

server/perfkit/explorer/handlers/templates/explorer.html
The 'auto' setting will use the current site's domain for the cookie, which is preferable to assuming the current 'googleplex.com' behavior.
=> Change cookie domain from googleplex.com to auto

bower.json, client/components/widget/widget-directive.css
Angular Material v11.x breaks the layout directive, so we will wait for 1.0 (the next release) to update.
=> Revert Angular Material to 10.1, remove CSS workaround

client/components/container/container-config-directive.css, client/components/container/container-config-directive.html, client/components/container/container-model.js, client/components/dashboard/dashboard-directive.html, client/components/widget/widget-directive.css
Provides a UX for setting the height of the container or widget's header/footer heights.  If a height is not specified, the section is auto-sized.  If a height is specified, the section will overflow with a scrollable region.
=> Container/Widget Header/Footer Sizing

client/karma.conf.js
Markdown dependencies weren't originally added to karma.conf.js, leading to test failures.
=> Add new dependencies to tests.

server/perfkit/explorer/handlers/templates/dashboard-admin.html, server/perfkit/explorer/handlers/templates/explorer.html
* GViz now uses a new loader library, with improved performance.
* AngularJS is now loaded at runtime, after gviz and the document have loaded.
* Moved script loading to the end of body, per Angular best-practice recommendations.
=> Updates to gviz and angular initialization.

server/perfkit/explorer/handlers/templates/dashboard-admin.html, server/perfkit/explorer/handlers/templates/explorer.html
This is deployed at https://26-1-dot-perfkit-explorer.appspot.com, and fixes an issue with the release that was mis-styling the tab icons and color pickers.
=> Load perfkit_styles.css last to correct override order.

client/components/widget/data_viz/gviz/gviz-directive.html, client/components/widget/data_viz/gviz/gviz-directive.js, client/components/widget/data_viz/gviz/gviz-directive_test.js, client/components/widget/widget-directive.css
Make status display conditional using CSS classes, this reduces the amount of
ng-show dependent code in gviz-directive.html.
Also disable animations for gviz chart elements, these were doing horrific
things to logic due to "animating" adding/removing classes so that
states ended up in a weird superposition of states that were meant to be
mutually exclusive.
=> gviz status display and animation refactor.

client/components/widget/data_viz/gviz/gviz-charts.json, server/perfkit/explorer/handlers/templates/dashboard-admin.html, server/perfkit/explorer/handlers/templates/explorer.html
Timeline and Treemap controls will be re-enabled when an issue with DataView binding has been resolved (gviz bug)
=> Update GViz charts to v43, remove Timeline & Treemap controls

client/components/widget/query/widget-editor-directive.css
From http://crbug.com/546034#c6 :
[IF THIS BREAKS ANY CONTENT/CHROME UI: Please do not revert this change.
Instead, add "min-width: 0; min-height: 0; to your flex items, which
should fix any issues that may occur]
=> Workaround for flex layout problems on Chrome 48

client/components/widget/query/widget-editor-directive.css, client/css/base.css
Replace the hack specific to the bottom SQL editor with a more generic
fix.
=> Update the flex-for-Chrome-48 fix to handle widget deletion also.

client/components/dashboard/dashboard-service.js, client/components/explorer/explorer-service.js
The code appeared to be calling rewriteQuery for side effect,
discarding the freshly constructed query. Clarify the API
to document the return value and use it.
=> Fix viewSQL usage of rewriteQuery

client/components/dashboard/dashboard-service.js, client/components/widget/data_viz/gviz/gviz-directive.js
Commit b1c9805 had removed duplicated logic from refreshWidget,
but this code appears to be required. Move the code and use it
from both refreshWidget and applyParameters.
For a freshly-created QueryBuilder graph, applyParameters never
gets called since it's conditional on datasource.query being
nonempty, so the query needs to be created in refreshWidget.
=> Move query-rebuilding logic, apply when refreshing.

client/app.js, client/components/dashboard/dashboard-directive.html, client/components/dashboard/dashboard-directive.js, client/components/dashboard/dashboard-directive_test.js, client/components/widget/widget-service.js, client/components/widget/widget-service_test.js, client/components/widget/widget-toolbar-directive.js, client/components/widget/widget-toolbar-directive_test.js
When deleting a widget from the toolbar or the widget itself, show a confirmation dialog that includes the widget title, if provided.
=> Confirm on widget delete

client/components/dashboard/dashboard-directive.html
Prevents loss of dashboard data due to inadvertent link clicking.
=> Open widget URL's in a new window.

gulpfile.js
The Closure compiler warnings patch had the wrong destination for its output, so recompiling didn't properly update the code. Fix the path.
=> Fix Closure compiler path.

client/components/widget/data_viz/gviz/gviz-directive.js, client/components/widget/widget-directive.js
This prevents spurious scrollbars from appearing on charts.  Note this issue only repros on Linux/Chrome, not OSX/Chrome.
Demo is at https://27-1-dot-perfkit-explorer.googleplex.com
=> Add width/height offset for chart sizing to deal with Linux/Chrome Issue

server/perfkit/common/big_query_result_pivot.py, server/perfkit/explorer/handlers/data.py
This resolves an issue where certain pivot errors were returning an empty string.
=> Add error messaging to pivot DuplicateValueError failures

client/components/widget/query/query-result-data-service.js
This has been an issue for error conditions, as well as certain cases with text/cloudsql widgets.
Demo is at https://27-1-dot-perfkit-explorer.googleplex.com
=> Suppress errors when a request contains no job id

client/components/widget/data_viz/gviz/gviz-directive.js, client/components/widget/query/query-result-data-service.js, client/components/widget/query/query-result-data-service_test.js
In cases where error messages aren't returning a string, Explorer is silently failing, and the widget will continue to appear in a loading state.  This fixes the issue so that "An unexpected error occurred" appears if no error text is provided.
=> Fixes silent failure issues

client/components/dashboard/dashboard-directive.html, client/components/widget/data_viz/gviz/gviz-directive.js, client/components/widget/widget-directive.css, client/css/base.css
* Add padding to widget body.
* Change widget selection color to *widget blue*.
* Fixed a "jumpy title" issue.
* Improvements to Chart/fill layout behavior.
* Modified heading styles to match [Material Design Typography](https://www.google.com/design/spec/style/typography.html) specifications.
=> UX Updates

client/components/dashboard_admin_page/dashboard-admin-page-controller.js
This change causes the Dashboard Title to behave like an anchor tag -- the context menu contains "copy this link", and using SHIFT and CTRL open in new tab/windows as expected.
=> Update dashboard title in admin to use link href instead of onclick

README.md
Updated README to reflect proper usage of `--project_id` flag when
loading data. I am not entirely sure why it is only with `bq load`
that you have to use `--project_id=` yet the rest of the times `bq` uses
`--project=`
=> Updated README to reflect proper usage of --project_id flag
